export const DaoABI = {
  address: "0x160c30b861d6e3ac4864903423e6523a2ed873ae1b41132382f699b07ac684ec",
  name: "Dao",
  friends: [],
  exposed_functions: [
    {
      name: "cast_vote",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "u64", "bool"],
      return: [],
    },
    {
      name: "compare_bytes",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["vector<u8>", "vector<u8>"],
      return: ["bool"],
    },
    {
      name: "create_dao",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "vector<u8>",
        "vector<u8>",
        "vector<u8>",
        "vector<address>",
      ],
      return: [],
    },
    {
      name: "create_proposal",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>"],
      return: [],
    },
    {
      name: "finalize_voting",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [],
    },
    {
      name: "get_backdrop",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<u8>"],
    },
    {
      name: "get_dao_info",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address"],
      return: [
        "address",
        "vector<u8>",
        "vector<u8>",
        "vector<u8>",
        "vector<address>",
        "u64",
      ],
    },
    {
      name: "get_logo",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<u8>"],
    },
    {
      name: "get_proposal_description",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "u64"],
      return: ["vector<u8>"],
    },
    {
      name: "get_proposal_id",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "u64"],
      return: ["u64"],
    },
    {
      name: "get_proposal_status",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "u64"],
      return: ["u8"],
    },
    {
      name: "get_vote_counts",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "u64"],
      return: ["u64", "u64"],
    },
    {
      name: "has_voted",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "u64", "address"],
      return: ["bool", "bool"],
    },
    {
      name: "is_council_member",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address", "address"],
      return: ["bool"],
    },
    {
      name: "start_voting",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [],
    },
  ],
  structs: [
    {
      name: "DAO",
      is_native: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "owner",
          type: "address",
        },
        {
          name: "name",
          type: "vector<u8>",
        },
        {
          name: "logo",
          type: "vector<u8>",
        },
        {
          name: "backdrop",
          type: "vector<u8>",
        },
        {
          name: "council",
          type: "vector<address>",
        },
        {
          name: "proposals",
          type: "vector<0x160c30b861d6e3ac4864903423e6523a2ed873ae1b41132382f699b07ac684ec::Dao::Proposal>",
        },
        {
          name: "proposal_count",
          type: "u64",
        },
      ],
    },
    {
      name: "Proposal",
      is_native: false,
      abilities: ["store"],
      generic_type_params: [],
      fields: [
        {
          name: "id",
          type: "u64",
        },
        {
          name: "description",
          type: "vector<u8>",
        },
        {
          name: "status",
          type: "u8",
        },
        {
          name: "yes_votes",
          type: "vector<address>",
        },
        {
          name: "no_votes",
          type: "vector<address>",
        },
      ],
    },
  ],
} as const;
