[package]
name = "VoteDAO"
version = "1.0.0"
authors = []

[addresses]
my_addrx = "0xd2a72a619bba781a73de84ff4d6ca8512322499ddc263ad7587a116a993f1bce"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
