[package]
name = "VoteDAO"
version = "1.0.0"
authors = []

[addresses]
my_addrx = "0x4c1081ce9b88b1ecf27142452f32174eadc0c7aaa07b5cf639f1ec62c1f09843"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
