[package]
name = "VoteDAO"
version = "1.0.0"
authors = []

[addresses]
my_addrx = "0x17b47e23b297e1383b179b72dc452e5e473f05142043ded32eb2f4cee924ab1d"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
